export const experiences = {
  portuguese: {
    txai: {
      position: "Desenvolvedor de Software",
      nameAndDescription: "Grupo Txai • Tempo integral",
      start: new Date(2022, 6, 18),
      end: null,
      deliveries: [
        "Atualmente, trabalho na Sistema Gestãol TXAI desenvolvendo sistemas internos para a gestão de cartórios em todo o Brasil. Meu foco é integrar o setor financeiro à tecnologia, promovendo eficiência operacional, escalabilidade e tomada de decisões baseada em dados, minhas principais entregas são:",
        "Redução de 70% no tempo de geração e análise de relatórios por meio da integração de IA generativa usando ChatGPT e Gemini.",
        "Automatizei fluxos de trabalho financeiros críticos para a empresa, reduzindo significativamente o processamento manual e aumentando a eficiência operacional em até 30%.",
        "Desenvolvi funcionalidades escaláveis ​​e capacidades de plataforma que apoiaram a aquisição de clientes e as iniciativas de expansão dos negócios, o que aumentou consideravelmente a receita.",
        "Desenvolvi aplicações escaláveis ​​usando React, Next.js, TypeScript, Node.js e NestJS.",
        "Implementei soluções de monitoramento e observabilidade com Prometheus e Grafana.",
        "Criei pipelines de CI/CD automatizados usando GitHub Actions, GitLab CI/CD e Jenkins.",
        "Desenvolvi arquiteturas orientadas a eventos e cache global para reutilizar textos gerados por IA usando Apache Kafka e Redis.",
        "Provisionei infraestrutura em nuvem usando AWS, GCP, Docker, Kubernetes e Terraform. Tive um impacto significativo na otimização de bancos de dados PostgreSQL, MySQL e MongoDB para desempenho e escalabilidade.",
      ],
    },
    nurv: {
      position: "Desenvolvedor FullStack",
      nameAndDescription: "Nurv • Freelance",
      start: new Date(2021, 6, 16),
      end: new Date(2022, 6, 18),
      deliveries: [
        "Trabalhei como desenvolvedor de software em projetos freelance, participando do desenvolvimento de websites, aplicativos, APIs e servidores, com foco na entrega de soluções personalizadas para diversos clientes. Atuei em um ambiente dinâmico, com projetos de curto e médio prazo (de 3 a 12 meses), priorizando demandas urgentes e entregas rápidas, sempre com foco na qualidade e na satisfação do cliente, minhas principais entregas são:",
        "Desenvolvi e mantive aplicações web, aplicações móveis e APIs para múltiplos projetos de clientes usando React, Next.js, React Native, Angular, Vue.js, Node.js e NestJS.",
        "Entreguei soluções de software completas, desde a arquitetura e o desenvolvimento até a implantação e o suporte à produção.",
        "Configurei e gerenciei infraestrutura em nuvem usando AWS e GCP, garantindo a disponibilidade e a consistência das implantações de aplicativos.",
        "Resolvi problemas de produção e implementei otimizações de desempenho, melhorando a estabilidade do aplicativo e a experiência do usuário.",
        "Colaborei diretamente com as partes interessadas para traduzir os requisitos de negócios em soluções técnicas escaláveis.",
        "Participei de diversos projetos de curto e médio prazo, entregando soluções prontas para produção dentro de prazos apertados.",
      ],
    },
  },
  english: {
    txai: {
      position: "Software Developer",
      nameAndDescription: "Grupo Txai • Full-time",
      start: new Date(2022, 6, 18),
      end: null,
      deliveries: [
        "Currently, I work at Sistema Gerencial TXAI developing internal systems for the management of notary offices throughout Brazil. My focus is on integrating the financial sector with technology, promoting operational efficiency, scalability, and data-driven decision making, my main deliverables:",
        "Reduced report generation and analysis time by 70% through Generative AI integration using ChatGPT and Gemini.",
        "I automated critical financial workflows for the company, significantly reducing manual processing and increasing operational efficiency by up to 30%.",
        "I developed scalable functionalities and platform capabilities that supported customer acquisition and business expansion initiatives, which considerably increased revenue.",
        "Developed scalable applications using React, Next.js, TypeScript, Node.js and NestJS.",
        "Implemented monitoring and observability solutions with Prometheus and Grafana.",
        "Built automated CI/CD pipelines using GitHub Actions, GitLab CI/CD and Jenkins.",
        "I developed event-driven architectures and global caching to reuse AI-generated texts using Apache Kafka and Redis.",
        "I provisioned cloud infrastructure using AWS, GCP, Docker, Kubernetes, and Terraform. I had a significant impact on optimizing PostgreSQL, MySQL, and MongoDB databases for performance and scalability.",
      ],
    },
    nurv: {
      position: "FullStack Developer",
      nameAndDescription: "Nurv • Freelancer",
      start: new Date(2021, 6, 16),
      end: new Date(2022, 6, 18),
      deliveries: [
        "I worked as a software developer on freelance projects, participating in the development of websites, applications, APIs, and servers, focusing on delivering customized solutions for various clients. I worked in a dynamic environment, with short and medium-term projects (3 to 12 months), prioritizing urgent demands and quick deliveries, always focusing on quality and client satisfaction, my main deliverables:",
        "Developed and maintained web applications, mobile applications and APIs for multiple client projects using React, Next.js, React Native, Angular, Vue.js, Node.js and NestJS.",
        "Delivered end-to-end software solutions from architecture and development to deployment and production support.",
        "Configured and managed cloud infrastructure using AWS and GCP, ensuring application availability and deployment consistency.",
        "Resolved production issues and implemented performance optimizations, improving application stability and user experience.",
        "Collaborated directly with stakeholders to translate business requirements into scalable technical solutions.",
        "Participated in multiple short and medium-term projects, delivering production-ready solutions under tight deadlines.",
      ],
    },
  },
};
