export const textAboutMe = {
  portuguese: [
    "Desenvolvedor de Software Sênior com mais de 4 anos de experiência, atuando no desenvolvimento, engenharia e evolução de sistemas escaláveis no setor financeiro. Hoje, sou referência técnica dentro do time de desenvolvimento, liderando iniciativas que conectam tecnologia ao negócio, promovendo eficiência operacional, tomada de decisão orientada por dados e integração com soluções de IA, como o Gemini.",
    "Atualmente, sou responsável pela manutenção e evolução dos produtos desenvolvidos com Typescript, React, Next.js, Node.js, NestJS, React Native, Vue e Angular. Fui responsável por definir e implementar a arquitetura das aplicações, projetadas como uma solução pronta para uso e altamente escalável, derivada do principal produto da empresa para gestão de cartórios, combinando tecnologia com o setor financeiro.",
    "Para garantir a qualidade do software, implementei uma estratégia robusta de testes automatizados (unitários, integração e E2E), utilizando Jest e Cypress, além da automação de pipelines com CI/CD. Atuo sempre seguindo boas práticas de engenharia de software, como Clean Code, SOLID e TDD.",
    "Dentro da equipe, exerço papel de liderança técnica, sendo responsável pelos Code Reviews, padronização de código, conduzindo projetos de ponta a ponta — desde a definição de requisitos até o deploy em produção — além de contribuir com documentação de código, criação de arquiteturas escalaveis e evolução contínua do código sempre visando boas praticas de programação.",
    "Responsável pela infraestrutura da empresa, atuando com AWS e GCP (Google Cloud Platform). Trabalho com Docker, Kubernetes, Terraform e Kafka na construção e orquestração de ambientes distribuídos, utilizando práticas de infraestrutura como código (IaC) e arquiteturas orientadas a eventos. Nesse contexto, liderei a configuração de ambientes, servidores e domínios, garantindo alta disponibilidade e eficiência na entrega dos serviços. Além disso, utilizo Redis, Prisma, MySQL, PostgreSQL e MongoDB na otimização e modelagem de dados.",
  ],
  english: [
    "Senior Software Developer with over 4 years of experience, participating in the development, engineering, and evolution of scalable systems in the financial sector. Currently, I am a technical reference in the development timeline, leading initiatives that connect technology to business, promoting operational efficiency, data-driven decision making, and integration with AI solutions such as Gemini.",
    "Currently, I am responsible for the maintenance and evolution of products developed with Typescript, React, Next.js, Node.js, NestJS, React Native, Vue, and Angular. I was responsible for defining and implementing the application architecture, designed as a ready-to-use and highly scalable solution, derived from the company's main product for notary office management, combining technology with the financial sector.",
    "To ensure software quality, I implemented a robust automated testing strategy (unit, integration, and E2E) using Jest and Cypress, in addition to pipeline automation with CI/CD. I always work following good software engineering practices, such as Clean Code, SOLID, and TDD.",
    "Within the team, I play a technical leadership role, being responsible for code reviews, code standardization, leading end-to-end projects — from requirements definition to production deployment — as well as contributing to code documentation, creating scalable architectures, and continuous code evolution, always involving good programming practices.",
    "Responsible for creating the company's network infrastructure, integrated with AWS and GCP (Google Cloud Platform). I work with Docker, Kubernetes, Terraform, and Kafka in building and orchestrating distributed environments, using Infrastructure as Code (IaC) practices and event-driven architectures. In this context, I led the configuration of environments, servers, and domains, ensuring high availability and efficiency in service delivery. Additionally, I utilize Redis, Prisma, MySQL, PostgreSQL, and MongoDB for data optimization and modeling.",
  ],
};
