export const textAboutMe = {
  portuguese: [
    "Engenheiro de Software Full-Stack com mais de 5 anos de experiência na criação de aplicações web escaláveis, aplicações móveis, plataformas nativas da nuvem, sistemas distribuídos e soluções com inteligência artificial. Ao longo da minha carreira, trabalhei em todo o ciclo de vida do desenvolvimento de software, desde arquitetura e design de infraestrutura até frontend, backend, DevOps, observabilidade, monitoramento, automação, integração de IA e suporte à produção.",
    "Minha experiência abrange TypeScript, React, Next.js, React Native, Node.js, NestJS, AWS, Kubernetes, Redis, Kafka, Terraform e tecnologias de IA generativa. Tenho experiência em projetar arquiteturas escaláveis, automatizar processos de negócios, construir sistemas orientados a eventos e entregar soluções de software confiáveis ​​em ambientes de nuvem. Sou apaixonado por resolver desafios complexos de negócios por meio da tecnologia, com forte foco em escalabilidade, desempenho, automação e eficiência operacional. Meus trabalhos recentes incluem iniciativas de automação baseadas em IA que reduziram o tempo de geração de relatórios em 70%, automação de fluxos de trabalho financeiros, implementação de arquiteturas nativas da nuvem, automação de CI/CD e otimização de processos de negócios em larga escala.",
    "Dentro da equipe de desenvolvimento, desempenho um papel de liderança técnica, sendo responsável por revisões de código, padronização de código, liderança de projetos de ponta a ponta, desde a definição de requisitos até a implantação em produção, além de contribuir para a documentação do código, criação de arquiteturas escaláveis ​​e evolução contínua do código, sempre envolvendo boas práticas de programação.",
    "Uma das minhas principais áreas de interesse é o uso da Inteligência Artificial para automatizar fluxos de trabalho, gerar e analisar conteúdo, otimizar processos operacionais e aprimorar a experiência do usuário. Também possuo vasta experiência com sistemas distribuídos, estratégias de cache global utilizando Redis, orquestração de contêineres com Kubernetes e automação de infraestrutura em nuvem. Gosto de desenvolver produtos que gerem valor comercial mensurável, mantendo altos padrões de qualidade, confiabilidade, escalabilidade e facilidade de manutenção do software.",
  ],
  english: [
    "Full-Stack Software Engineer with over 5 years of experience building scalable web applications, mobile applications, cloud-native platforms, distributed systems, and AI-powered solutions. Throughout my career, I have worked across the entire software development lifecycle, from architecture and infrastructure design to frontend, backend, DevOps, observability, monitoring, automation, AI integration and production support.",
    "My expertise includes TypeScript, React, Next.js, React Native, Node.js, NestJS, AWS, Kubernetes, Redis, Kafka, Terraform, and Generative AI technologies. I have experience designing scalable architectures, automating business processes, building event-driven systems, and delivering reliable software solutions in cloud environments. I am passionate about solving complex business challenges through technology, with a strong focus on scalability, performance, automation, and operational efficiency. My recent work includes AI-powered automation initiatives that reduced report generation time by 70%, automation of financial workflows, implementation of cloud-native architectures, CI/CD automation, and optimization of large-scale business processes.",
    "Within the development team, I play a technical leadership role, being responsible for code reviews, code standardization, leading end-to-end projects from requirements definition to production deployment as well as contributing to code documentation, creating scalable architectures, and continuous code evolution, always involving good programming practices.",
    "One of my key areas of interest is leveraging Artificial Intelligence to automate workflows, generate and analyze content, optimize operational processes, and improve user experiences. I also have extensive experience with distributed systems, global caching strategies using Redis, container orchestration with Kubernetes, and cloud infrastructure automation. I enjoy building products that create measurable business value while maintaining high standards of software quality, reliability, scalability, and maintainability.",
  ],
};
